# Site Settings
title: My Resume
url: 'http://garciaErick.github.io'
baseurl: '/online-cv' #change it according to your repository name
about: True
port: 8080

style: styles-6


#Profile information
name: Erick Garcia
tagline: Full Stack Developer
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
logo: logo_white.png
summary: 'Summarise your career here lorem ipsum dolor sit amet, consectetuer adipiscing elit.
You can <a href="#" target="_blank">download this free resume/CV template here</a>. Aenean
commodo ligula eget dolor aenean massa. Cum sociis natoque penatibus et magnis dis parturient
montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu.'

#sidebar links
email: me@erick-garcia.com
phone: +52 1 656 375 6477 (Mexico)
website: erick-garcia.com
linkedin: garciaErickCs
github: garciaErick
twitter: @blaksephirot

#Update all the sections by editing the files inside _data folder.
#education_in_main: True

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html:
  clippings: all
  ignore:
    envs: development
